In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [25]:
df1 = pd.read_csv('../../data/pre-clean data/Received Mental Health Services in Past Year- Among People Aged 18 or Older; by Demographic Characteristics, Numbers in Thousands, 2002-2020.csv')
df2 = pd.read_csv('../../data/pre-clean data/Received Mental Health Services in Past Year- Among People Aged 18 or Older; by Geographic and Socioeconomic Characteristics, Numbers in Thousands, 2002-2020.csv')
df1.rename(columns = {'Demographic Characteristic':''}, inplace = True)
df2.rename(columns = {'Geographic/Socioeconomic Characteristic':''}, inplace = True)
df = pd.concat([df1,df2], ignore_index = True)
df = df.drop(df.index[[0,1,3,6,9,13,14,18,19,24,31,32,33,34,35,40,41,42,43,44]])

df = df.apply(lambda x: x.str.replace('Northeast', 'Northeast Region'))
df = df.apply(lambda x: x.str.replace('Midwest', 'Midwest Region'))
df = df.apply(lambda x: x.str.replace('South', 'South Region'))
df = df.apply(lambda x: x.str.replace('West', 'West Region'))
df = df.apply(lambda x: x.str.replace('Large Metro', 'Large Metro Resident'))
df = df.apply(lambda x: x.str.replace('Small Metro', 'Small Metro Resident'))
df = df.apply(lambda x: x.str.replace('Nonmetro', 'Non Metro Resident'))
df = df.apply(lambda x: x.str.replace('50 or Older', '50+'))

df = df.replace(',','', regex=True)
df = df.apply(lambda x: x.str.replace('nc', ''))
df = df.apply(lambda x: x.str.strip()).replace('', np.nan)

df['2002'] = pd.to_numeric(df['2002']).astype('float')
df['2003'] = pd.to_numeric(df['2003']).astype('float')
df['2004'] = pd.to_numeric(df['2004']).astype('float')
df['2005'] = pd.to_numeric(df['2005']).astype('float')
df['2006'] = pd.to_numeric(df['2006']).astype('float')
df['2007'] = pd.to_numeric(df['2007']).astype('float')
df['2008'] = pd.to_numeric(df['2008']).astype('float')
df['2009'] = pd.to_numeric(df['2009']).astype('float')
df['2010'] = pd.to_numeric(df['2010']).astype('float')
df['2011'] = pd.to_numeric(df['2011']).astype('float')
df['2012'] = pd.to_numeric(df['2012']).astype('float')
df['2013'] = pd.to_numeric(df['2013']).astype('float')
df['2014'] = pd.to_numeric(df['2014']).astype('float')
df['2015'] = pd.to_numeric(df['2015']).astype('float')
df['2016'] = pd.to_numeric(df['2016']).astype('float')
df['2017'] = pd.to_numeric(df['2017']).astype('float')
df['2018'] = pd.to_numeric(df['2018']).astype('float')
df['2019'] = pd.to_numeric(df['2019']).astype('float')
df['2020'] = pd.to_numeric(df['2020']).astype('float')

In [26]:
df

,,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
2,18-25,3256,3511,3459,3615,3526,3387,3612,3740,3717,3899,4120,4221,4135,4044,4423,5073,5120,5756,6347
4,26-49,14492,14476,14348,13889,14054,14311,14030,14481,14627,14543,14811,15101,14930,15057,15154,15695,16113,17931,17978
5,50+,9466,9952,9695,10661,10825,11857,12559,12120,13146,13200,15191,15322,16432,15142,15404,15647,15868,16466,17118
7,Male,8772,8689,9044,9308,9484,9876,10141,10131,10519,11051,11519,11557,12190,11945,11632,12462,12096,13428,13293
8,Female,18442,19250,18458,18858,18921,19680,20060,20210,20970,20592,22603,23087,23308,22298,23350,23954,25006,26726,28151
10,Not Hispanic or Latino,25172,25919,25523,25999,26372,27394,28137,28071,28981,29180,31651,31549,32463,31187,31740,33086,33573,36188,37168
11,White,21943,22914,22512,22890,23330,24785,24818,24888,25418,25656,27638,27383,28079,27129,27793,28708,29151,31158,32397
12,Black or African American,1953,2021,2052,2193,1856,1711,2231,2044,2353,2035,2770,2460,2626,2476,2393,2525,2555,2897,2728
15,Asian,668,424,422,365,518,382,442,358,545,728,505,768,849,674,663,823,894,1012,805
16,Two or More Races,352,373,335,317,480,363,469,467,481,529,485,713,645,672,624,806,664,869,967
17,Hispanic or Latino,2043,2020,1979,2166,2033,2162,2064,2270,2509,2463,2471,3096,3035,3055,3242,3330,3528,3965,4275
20,Northeast Region,5581,5557,5397,5709,5540,6174,5749,5469,6292,5978,6113,6709,6793,6764,6971,6737,7369,7503,7273
21,Midwest Region,6160,6837,6577,6790,6755,6738,7046,7187,7266,7531,7858,8181,8274,7683,8461,8573,8868,9740,9985
22,South Region,9214,9871,9364,9976,9934,10394,10285,11141,10793,11236,12632,11970,12606,12067,12297,12875,12569,13503,14741
23,West Region,6259,5674,6164,5690,6177,6249,7121,6544,7140,6897,7519,7784,7826,7729,7253,8232,8296,9407,9445
25,Large Metro Resident,14472,14466,14225,14415,14907,14976,15922,15521,16444,16018,17730,18432,18976,18551,18884,19633,19362,21410,20928
26,Small Metro Resident,8615,9032,9034,9181,8483,9594,9654,10108,10305,11002,11099,11062,11192,11210,11115,11627,12252,12970,14435
27,Non Metro Resident,4128,4441,4243,4569,5016,4986,4624,4712,4741,4622,5293,5150,5330,4481,4983,5156,5486,5774,6081
28,Urbanized,1936,1947,1856,1742,1893,2150,2038,1807,2097,1786,2316,2303,2245,1977,1905,2233,2585,2557,2367
29,Less Urbanized,1887,2057,2017,2360,2604,2433,2244,2432,2175,2491,2477,2397,2561,1957,2623,2425,2338,2684,3045
30,Completely Rural,305,437,370,467,520,403,341,473,469,346,500,450,523,547,455,498,563,532,670
36,< High School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3239,3361,3239,3172,3382,3315
37,High School Graduate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7634,7291,7224,7167,7939,9241
38,Some College/Associate’s Degree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11714,12243,12696,12994,13772,13513
39,College Graduate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11656,12087,13257,13768,15061,15376