In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [55]:
df1 = pd.read_csv('../../data/pre-clean data/Any Mental Illness in Past Year- Among People Aged 18 or Older; by Demographic Characteristics, Numbers in Thousands, 2008-2020.csv')
df2 = pd.read_csv('../../data/pre-clean data/Any Mental Illness in Past Year- Among People Aged 18 or Older; by Geographic and Socioeconomic Characteristics, Numbers in Thousands, 2008-2020.csv')
df1.rename(columns = {'20081':'2008'}, inplace = True)
df1.rename(columns = {'Demographic Characteristic':''}, inplace = True)
df1 = df1.drop(df1.index[[0,1,3,6,9,13,14]])
df1 = df1.apply(lambda x: x.str.replace('50 or Older', '50+'))

df2.rename(columns = {'20081':'2008'}, inplace = True)
df2.rename(columns = {'Geographic/Socioeconomic Characteristic':''}, inplace = True)
df2 = df2.drop(df2.index[[0,1,6,12,13,14,15,16,17,22,23,24,25,26]])

df = pd.concat([df1,df2], ignore_index = True)

df = df.apply(lambda x: x.str.replace('Northeast', 'Northeast Region'))
df = df.apply(lambda x: x.str.replace('Midwest', 'Midwest Region'))
df = df.apply(lambda x: x.str.replace('South', 'South Region'))
df = df.apply(lambda x: x.str.replace('West', 'West Region'))
df = df.apply(lambda x: x.str.replace('Large Metro', 'Large Metro Resident'))
df = df.apply(lambda x: x.str.replace('Small Metro', 'Small Metro Resident'))
df = df.apply(lambda x: x.str.replace('Nonmetro', 'Non Metro Resident'))

df = df.replace(',','', regex=True)
df = df.apply(lambda x: x.str.replace('nc', ''))
df = df.apply(lambda x: x.str.strip()).replace('', np.nan)

df['2008'] = pd.to_numeric(df['2008']).astype('float')
df['2009'] = pd.to_numeric(df['2009']).astype('float')
df['2010'] = pd.to_numeric(df['2010']).astype('float')
df['2011'] = pd.to_numeric(df['2011']).astype('float')
df['2012'] = pd.to_numeric(df['2012']).astype('float')
df['2013'] = pd.to_numeric(df['2013']).astype('float')
df['2014'] = pd.to_numeric(df['2014']).astype('float')
df['2015'] = pd.to_numeric(df['2015']).astype('float')
df['2016'] = pd.to_numeric(df['2016']).astype('float')
df['2017'] = pd.to_numeric(df['2017']).astype('float')
df['2018'] = pd.to_numeric(df['2018']).astype('float')
df['2019'] = pd.to_numeric(df['2019']).astype('float')
df['2020'] = pd.to_numeric(df['2020']).astype('float')

In [56]:
df

,,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,18-25,6099.0,6043.0,6151.0,6356.0,6774.0,6754.0,7014.0,7574.0,7635.0,8849.0,8944.0,9930.0,10238.0
1,26-49,20697.0,21455.0,20648.0,19936.0,20777.0,21061.0,20007.0,20589.0,20903.0,22256.0,22721.0,25279.0,25676.0
2,50+,13030.0,13698.0,14618.0,15089.0,16163.0,16031.0,16531.0,15257.0,16114.0,15527.0,15969.0,16286.0,16945.0
3,Male,14778.0,15614.0,16461.0,15895.0,16856.0,16452.0,16371.0,16785.0,17142.0,18065.0,18308.0,19758.0,19269.0
4,Female,25048.0,25581.0,24956.0,25486.0,26858.0,27394.0,27182.0,26636.0,27510.0,28567.0,29327.0,31737.0,33590.0
5,Not Hispanic or Latino,34971.0,36321.0,36580.0,36793.0,38049.0,37828.0,37795.0,37919.0,38598.0,40603.0,40785.0,44055.0,45115.0
6,White,28286.0,29799.0,29704.0,29552.0,30066.0,30222.0,30074.0,30387.0,31266.0,32183.0,32210.0,34967.0,35621.0
7,Black or African American,4314.0,4113.0,4520.0,4364.0,5044.0,4688.0,4603.0,4410.0,4171.0,4782.0,4802.0,5174.0,5269.0
8,Asian,1300.0,1287.0,1425.0,1473.0,1608.0,1489.0,1653.0,1620.0,1602.0,2000.0,2081.0,2100.0,1995.0
9,Two or More Races,666.0,757.0,584.0,847.0,709.0,995.0,989.0,1142.0,1061.0,1198.0,1160.0,1390.0,1689.0
10,Hispanic or Latino,4855.0,4874.0,4837.0,4589.0,5665.0,6018.0,5758.0,5502.0,6053.0,6028.0,6850.0,7440.0,7744.0
11,Northeast Region,7865.0,7587.0,7890.0,6966.0,7723.0,7701.0,7666.0,7706.0,7910.0,7920.0,8291.0,8608.0,8383.0
12,Midwest Region,9075.0,9169.0,9369.0,9020.0,9173.0,9461.0,9436.0,9167.0,8934.0,10230.0,10329.0,11497.0,11866.0
13,South Region,13905.0,14604.0,14656.0,15362.0,16282.0,16014.0,15877.0,16273.0,16638.0,16847.0,16946.0,18212.0,18616.0
14,West Region,8980.0,9835.0,9502.0,10033.0,10536.0,10670.0,10573.0,10275.0,11169.0,11634.0,12068.0,13178.0,13994.0
15,Large Metro Resident,21077.0,21986.0,21967.0,21234.0,23221.0,23763.0,23371.0,23474.0,24038.0,25223.0,25715.0,28346.0,27213.0
16,Small Metro Resident,12622.0,13011.0,13151.0,13905.0,14040.0,13492.0,13260.0,13832.0,14068.0,14626.0,15312.0,15837.0,17946.0
17,Non Metro Resident,6127.0,6198.0,6299.0,6243.0,6452.0,6591.0,6922.0,6114.0,6546.0,6782.0,6608.0,7312.0,7699.0
18,Urbanized,2554.0,2418.0,2500.0,2589.0,2646.0,2976.0,2975.0,2666.0,2461.0,2973.0,3153.0,3100.0,3360.0
19,Less Urbanized,2997.0,3222.0,3155.0,3170.0,3191.0,3047.0,3260.0,2731.0,3491.0,3214.0,2820.0,3554.0,3629.0
20,< High School,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5822.0,5538.0,5320.0,5628.0,5505.0,5552.0
21,High School Graduate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10621.0,10813.0,10343.0,11110.0,11705.0,13170.0
22,Some College/Associate’s Degree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15450.0,15797.0,16525.0,17171.0,18250.0,18339.0
23,College Graduate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11528.0,12504.0,14444.0,13725.0,16034.0,15798.0