In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay,classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [10]:
x = df.drop('gender',axis=1)
y = df['gender']

normalize = StandardScaler()
normalize.fit(x)
x= normalize.transform(x)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [3]:
df

,18-25,26-49,50+,Male,Female,Not Hispanic or Latino,White,Black or African American,Asian,Two or More Races,Hispanic or Latino,Northeast Region,Midwest Region,South Region,West Region,Large Metro Resident,Small Metro Resident,Non Metro Resident,Urbanized,Less Urbanized
0,6099,20697,13030,14778,25048,34971,28286,4314,1300,666,4855,7865,9075,13905,8980,21077,12622,6127,2554,2997
1,6043,21455,13698,15614,25581,36321,29799,4113,1287,757,4874,7587,9169,14604,9835,21986,13011,6198,2418,3222
2,6151,20648,14618,16461,24956,36580,29704,4520,1425,584,4837,7890,9369,14656,9502,21967,13151,6299,2500,3155
3,6356,19936,15089,15895,25486,36793,29552,4364,1473,847,4589,6966,9020,15362,10033,21234,13905,6243,2589,3170
4,6774,20777,16163,16856,26858,38049,30066,5044,1608,709,5665,7723,9173,16282,10536,23221,14040,6452,2646,3191
5,6754,21061,16031,16452,27394,37828,30222,4688,1489,995,6018,7701,9461,16014,10670,23763,13492,6591,2976,3047
6,7014,20007,16531,16371,27182,37795,30074,4603,1653,989,5758,7666,9436,15877,10573,23371,13260,6922,2975,3260
7,7574,20589,15257,16785,26636,37919,30387,4410,1620,1142,5502,7706,9167,16273,10275,23474,13832,6114,2666,2731
8,7635,20903,16114,17142,27510,38598,31266,4171,1602,1061,6053,7910,8934,16638,11169,24038,14068,6546,2461,3491
9,8849,22256,15527,18065,28567,40603,32183,4782,2000,1198,6028,7920,10230,16847,11634,25223,14626,6782,2973,3214
10,8944,22721,15969,18308,29327,40785,32210,4802,2081,1160,6850,8291,10329,16946,12068,25715,15312,6608,3153,2820
11,9930,25279,16286,19758,31737,44055,34967,5174,2100,1390,7440,8608,11497,18212,13178,28346,15837,7312,3100,3554
12,10238,25676,16945,19269,33590,45115,35621,5269,1995,1689,7744,8383,11866,18616,13994,27213,17946,7699,3360,3629

In [12]:
clf = SVC(C=0.35, kernel = 'linear')
clf.fit(x_train,y_train)
yp_train = clf.predict(x_train)
yp_test = clf.predict(x_test)

cm_train = confusion_matrix(y_train, yp_train)
cm_test = confusion_matrix(y_test, yp_test)

target_names = ['Male', 'Female']

clf_report_linear = classification_report(y_train, yp_train,target_names=target_names, output_dict=True)
clf_report_linear = pd.DataFrame(clf_report_linear).transpose()

clf_report_linear

/Users/elliotli/opt/anaconda3/envs/ANLY501/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/elliotli/opt/anaconda3/envs/ANLY501/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/elliotli/opt/anaconda3/envs/ANLY501/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision  recall  f1-score  support
Male           0.762500  1.0000  0.865248  61.0000
Female         0.000000  0.0000  0.000000  19.0000
accuracy       0.762500  0.7625  0.762500   0.7625
macro avg      0.381250  0.5000  0.432624  80.0000
weighted avg   0.581406  0.7625  0.659752  80.0000